### PR TITLE
[irods/irods#7531] remove `EXACT` argument from `find_package(IRODS` call (4-3-stable)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
In service of irods/irods#7531

Merge irods/irods#7536 before merging this.

### CODE REVIEW

**Comment by korydraughn** [comment]
Will approve once we get a new release of this plugin for 4.3.1 done.

As of right now, 4-3-stable needs a couple tweaks before that can happen. The tweaks are related to https://github.com/irods/irods_rule_engine_plugin_metadata_guard/commit/55bb2b0fec5e2f5dce1f2dd7a79c0b2ea3a2cc2e.

**Comment by SwooshyCueb** [comment]
I've made this PR 4.3.1-compatible, so it shouldn't interfere with the release.

**Review by alanking — APPROVED** [review]
\# it when ready

**Comment by alanking** [comment]
Will merge after https://github.com/irods/irods_rule_engine_plugin_metadata_guard/pull/76

...unless @korydraughn has objections. I defer.

**Review by korydraughn — APPROVED** [review]
Pound it.

**Comment by alanking** [comment]
Please disregard my last comment. I referenced the wrong PR. :)

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
