### PR TITLE
[#78] Restore build compatibility with iRODS 4.3.1 packages

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #78

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Looks good. Does it compile against 4.3.1 packages?

**Comment by trel** [comment]
so readable and clean.    we must be from the future....

**Comment by SwooshyCueb** [comment]
> Looks good. Does it compile against 4.3.1 packages?

Yes indeed.

**Review by korydraughn — APPROVED** [review]
Ship it!

**Review by alanking — APPROVED** [review]
\# it when ready

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
